#!/usr/bin/env bash
set -euo pipefail

# DayZ Dashboard Debian setup script (Postgres-first)
# Usage:
#   sudo ./scripts/setup-debian.sh [--admin-discord-id ID] [--admin-email EMAIL] [--non-interactive]
#
# The script will:
#  - install Node.js (NodeSource) and basic build tools
#  - install PostgreSQL server (optional) and create a DB/user if needed
#  - install project dependencies (npm ci)
#  - create a .env file (Postgres by default) with generated secrets
#  - run DB migrations
#  - build Tailwind CSS
#  - optionally create an admin user
#  - optionally install pm2 and start the app (interactive prompt)

ADMIN_DISCORD_ID=""
ADMIN_EMAIL=""
NON_INTERACTIVE=0
PM2_AUTO=0
POSTGRES_DB_NAME="dayz_dashboard"
POSTGRES_USER_NAME="dayz"
POSTGRES_PASSWORD=""
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --admin-discord-id) ADMIN_DISCORD_ID="$2"; shift 2;;
    --admin-email) ADMIN_EMAIL="$2"; shift 2;;
    --non-interactive) NON_INTERACTIVE=1; shift 1;;
    --pm2) PM2_AUTO=1; shift 1;;
    --db-name) POSTGRES_DB_NAME="$2"; shift 2;;
    --db-user) POSTGRES_USER_NAME="$2"; shift 2;;
    --db-password) POSTGRES_PASSWORD="$2"; shift 2;;
    -h|--help) echo "Usage: $0 [--admin-discord-id ID] [--admin-email EMAIL] [--non-interactive] [--pm2] [--db-name NAME] [--db-user USER] [--db-password PWD]"; exit 0;;
    *) echo "Unknown arg: $1"; exit 2;;
  esac
done

if [ "$EUID" -ne 0 ]; then
  echo "This script may need to perform system installs. Re-run as root or with sudo." >&2
  echo "Continuing as non-root; sudo will be used for apt operations if available."
fi

SUDO_CMD=""
if command -v sudo >/dev/null 2>&1; then
  SUDO_CMD=sudo
fi

echo "=== DayZ Dashboard Debian setup (Postgres default) ==="

echo "Updating apt cache..."
$SUDO_CMD apt-get update -y

echo "Installing prerequisites (curl, ca-certificates, gnupg, build-essential, git)..."
$SUDO_CMD apt-get install -y curl ca-certificates gnupg build-essential git

# Install Node.js 22.x from NodeSource
if ! command -v node >/dev/null 2>&1 || [ "$(node -v | cut -d. -f1 | tr -d 'v')" -ne 22 ]; then
  echo "Installing Node.js 22.x (NodeSource)..."
  curl -fsSL https://deb.nodesource.com/setup_22.x | $SUDO_CMD bash -
  $SUDO_CMD apt-get install -y nodejs
else
  echo "Node.js present: $(node -v)"
fi

# Ensure npm is available
if ! command -v npm >/dev/null 2>&1; then
  echo "npm not found after Node install; aborting." >&2
  exit 1
fi

# Install PostgreSQL if not present
if ! command -v psql >/dev/null 2>&1; then
  echo "Postgres (psql) not found — installing postgresql..."
  $SUDO_CMD apt-get install -y postgresql postgresql-contrib
else
  echo "psql present: $(psql --version)"
fi

# Generate POSTGRES_PASSWORD if not supplied
if [ -z "$POSTGRES_PASSWORD" ]; then
  POSTGRES_PASSWORD=$(openssl rand -hex 16 || node -e "console.log(require('crypto').randomBytes(16).toString('hex'))")
fi

# Create Postgres role and database if they do not exist
create_pg_user_and_db() {
  DBNAME="$1"
  DBUSER="$2"
  DBPASS="$3"

  echo "Ensuring Postgres role '$DBUSER' and database '$DBNAME' exist..."

  # Check if role exists
  if $SUDO_CMD -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DBUSER}'" | grep -q 1; then
    echo "Postgres role ${DBUSER} already exists — skipping role creation"
  else
    echo "Creating Postgres role ${DBUSER}"
    $SUDO_CMD -u postgres psql -c "CREATE ROLE ${DBUSER} WITH LOGIN PASSWORD '${DBPASS}';"
  fi

  # Check if database exists
  if $SUDO_CMD -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DBNAME}'" | grep -q 1; then
    echo "Database ${DBNAME} already exists — skipping database creation"
  else
    echo "Creating database ${DBNAME} owned by ${DBUSER}"
    $SUDO_CMD -u postgres psql -c "CREATE DATABASE ${DBNAME} OWNER ${DBUSER};"
  fi

  # Ensure privileges
  $SUDO_CMD -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DBNAME} TO ${DBUSER};" || true
}

create_pg_user_and_db "$POSTGRES_DB_NAME" "$POSTGRES_USER_NAME" "$POSTGRES_PASSWORD"

# Install project dependencies
echo "Installing project dependencies (npm ci)..."
npm ci --no-audit --progress=false

# Create .env if missing
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo ".env already exists — skipping generation"
else
  echo "Generating .env with sensible defaults (Postgres)"
  SESSION_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")

  cat > "$ENV_FILE" <<EOF
# DayZ Dashboard environment (generated by scripts/setup-debian.sh)
# Edit values as needed.
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_DB_NAME}
POSTGRES_USER=${POSTGRES_USER_NAME}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

SESSION_SECRET=${SESSION_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Discord OAuth & bot settings - fill these before running in production
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_BOT_TOKEN=

# App
DEPLOYMENT_MODE=full
APP_NAME=DayZ Dashboard
DASHBOARD_URL=
PLAYER_PORTAL_URL=
DISCORD_INVITE_URL=
SESSION_SECURE_COOKIE=true
RATE_LIMIT_ENABLED=true
NODE_ENV=production

# Other optional tuning
PORT=3000

EOF
  echo "Created .env for PostgreSQL. Review and update Discord settings before production use."
fi

# Build Tailwind CSS
if grep -q "build:css" package.json 2>/dev/null; then
  echo "Building CSS (npm run build:css)..."
  npm run build:css
else
  echo "No build:css script found — skipping CSS build"
fi

echo "Initializing and verifying the PostgreSQL schema..."
node scripts/db-smoke-test.js

# Optionally create admin user
if [ -n "$ADMIN_DISCORD_ID" ] || [ -n "$ADMIN_EMAIL" ]; then
  echo "Setting admin user..."
  if [ -n "$ADMIN_DISCORD_ID" ]; then
    node scripts/set-admin.js --discordId "$ADMIN_DISCORD_ID" --username "admin"
  else
    node scripts/set-admin.js --email "$ADMIN_EMAIL" --username "admin"
  fi
else
  echo "No admin identity provided. Use scripts/set-admin.js later to create the admin user."
fi

# Optionally install and configure pm2 to run the app as services
# If run non-interactively (--non-interactive) or with --pm2, enable automatic pm2 setup
if [ "$NON_INTERACTIVE" -eq 1 ] || [ "$PM2_AUTO" -eq 1 ]; then
  PM2_CHOICE=Y
else
  read -p "Install pm2 and configure app to run under pm2? (recommended) [y/N]: " PM2_CHOICE
fi

if [[ "$PM2_CHOICE" =~ ^[Yy] ]]; then
  echo "Installing pm2 globally..."
  $SUDO_CMD npm install -g pm2
  echo "Starting apps under pm2 using ecosystem.config.js..."
  mkdir -p logs
  pm2 start ecosystem.config.js
  pm2 save
  echo "Configuring pm2 to start on boot (systemd)..."
  # Use sudo env to preserve PATH when called with sudo
  $SUDO_CMD env PATH=$PATH:/usr/bin pm2 startup systemd -u $(whoami) --hp $(eval echo ~$(whoami)) || true
  pm2 save
  echo "pm2 setup complete. Use 'pm2 status' to inspect processes."
else
  echo "Skipping pm2 installation. You can use systemd, docker-compose, or pm2 later to run the app."
fi

# Final message
cat <<EOF

=== Setup complete ===

Next steps:
 - Edit .env and populate DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET, DISCORD_BOT_TOKEN, BASE_URL
 - If you didn't create the admin user above, run:
     node scripts/set-admin.js --discordId <DISCORD_ID> --username "AdminName"
 - Start the app: npm run start (or use pm2/systemd)

EOF

exit 0
